---
title: "Instructions for Yet Another Rig Count App"

output: html_document
---


### Map Navigation
The map itself is navigated roughly the same way as all map software.  The zoom functionality is available either through the mouse wheel or holding shift + left click the area surrounding the area of interest.

The darker the "blue" color, the more rigs are in that county.

Click on any county to see the count of rigs currently working in that county.


### Rig Count Explorer Window
The explorer window on the right of the map can be used to filter for the particular data in question.  It is made up of:

* Date selector - slider bar to choose the date of the BHI rig count release.  Currenly, BHI only provides detailed data going back a few years.  The little "play" button will animate the map through time.
* Subsettng groups - 
..+ by default all rigs are shown
..+ particular rigs / groups can be chosen and will be updated on the map / time series chart.


### Time series chart
The time series chart tool is located on the bottom left of the map window.  
* The tool will show the historical rig counts of the counties __that are visible on the map__
* Grouping cand be performed by selected the group of interest from the drop down menu.
* selecting "stacked" will show a stacked line chart and "linear" will show the series graphed independently
* The window selector at the bottom can be utilized to choose the time period of interest, or you can just click and drag on the graph itself to zoom on on the time period of interest.

_Data is sourced from the Baker Hughes website and I have no idea if its accurate or not. Use at your own risk for absolutely nothing of value.  The information contained here is worth exactly what you paid for it, which is nothing_
